# Generated by Django 5.1 on 2024-08-18 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionAdministrativeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_code', models.CharField(max_length=10, verbose_name='Kode Wilayah')),
                ('reg_name', models.CharField(max_length=128, verbose_name='Nama Wilayah')),
            ],
        ),
        migrations.CreateModel(
            name='RegionSLSModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_sls_code', models.CharField(max_length=6, verbose_name='Kode SLS/Non SLS')),
                ('reg_sls_name', models.CharField(max_length=128, verbose_name='Nama SLS/Non SLS')),
                ('reg_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_administrative', to='app.regionadministrativemodels', verbose_name='Kode Desa/Kelurahan')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, editable=False)),
                ('r107', models.TextField(max_length=256, verbose_name='Alamat lengkap')),
                ('r108', models.CharField(max_length=128, verbose_name='Nama Kepala Keluarga (KK)')),
                ('r112', models.IntegerField(verbose_name='Jumlah Anggota Keluarga?')),
                ('r301a', models.CharField(choices=[('1', 'Milik Sendiri'), ('2', 'Kontrak/Sewa'), ('3', 'Bebas Sewa'), ('4', 'Dinas'), ('5', 'Lainnya')], max_length=1, verbose_name='Status kepemilikan bangunan tempat tinggal yang ditempati?')),
                ('r301b', models.CharField(blank=True, choices=[('1', 'SHM atas Nama Anggota Keluarga'), ('2', 'SHM bukan a.n Anggota Keluarga dengan Perjanjian Pemanfaatan Tertulis'), ('3', 'SHM bukan a.n Anggota Keluarga tanpa Perjanjian Pemanfaatan Tertulis'), ('4', 'Sertifikat selain SHM (SHGB, SHSRS)'), ('5', 'Surat Bukti Lainnya (Girik, Letter C, dll)'), ('6', 'Tidak punya')], max_length=1, null=True, verbose_name='Apa bukti kepemilikan tanah bangunan tempat tinggal saat ini?')),
                ('r302', models.IntegerField(verbose_name='Luas lantai bangunan tempat tinggal? ... m2')),
                ('r303', models.CharField(choices=[('1', 'Marmer/Granit'), ('2', 'Keramik'), ('3', 'Parket/Vini/Karpet'), ('4', 'Ubin/Tegel/Teraso'), ('5', 'Kayu/Papan'), ('6', 'Semen/Bata Merah'), ('7', 'Bambu'), ('8', 'Tanah'), ('9', 'Lainnya')], max_length=1, verbose_name='Apa jenis lantai terluas?')),
                ('r304', models.CharField(choices=[('1', 'Tembok'), ('2', 'Plesteran Anyaman Bambu/Kawat'), ('3', 'Kayu/Papan/Gypsum/GRC/Calciboard'), ('4', 'Anyaman Bambu'), ('5', 'Batang Kayu'), ('6', 'Bambu'), ('7', 'Lainnya')], max_length=1, verbose_name='Apa jenis dinding terluas?')),
                ('r305', models.CharField(choices=[('1', 'Beton'), ('2', 'Genteng'), ('3', 'Seng'), ('4', 'Asbes'), ('5', 'Bambu'), ('6', 'Kayu/Sirap'), ('7', 'Jerami/Ijuk/Daun-daunan/Numbia'), ('8', 'Lainnya')], max_length=1, verbose_name='Apa jenis atap terluas?')),
                ('r306a', models.CharField(choices=[('1', 'Air Kemasan Bermerk'), ('2', 'Air Isi Ulang'), ('3', 'Leding'), ('4', 'Sumur Bor/Pompa'), ('5', 'Sumur Terlindung'), ('6', 'Sumur Tak Terlindung'), ('7', 'Mata Air Terlindung'), ('8', 'Mata Air Tak Terlindung'), ('9', 'Air Permukaan (Sungai/Danau/Waduk/Kolam/Irigasi)'), ('10', 'Air Hujan'), ('11', 'Lainnya')], max_length=2, verbose_name='Apa sumber air minum utama?')),
                ('r306b', models.CharField(blank=True, choices=[('1', '< 10 Meter'), ('2', '>= 10 Meter'), ('8', 'Tidak Tahu')], max_length=1, null=True, verbose_name='Seberapa jauh jarak sumber air minum utama ke tempat penampungan limbah/kotoran/tinja terdekat?')),
                ('r307a', models.CharField(choices=[('1', 'Listrik PLN dengan meteran'), ('2', 'Listrik PLN tanpa meteran'), ('3', 'Listrik Non-PLN'), ('4', 'Bukan Listrik')], max_length=1, verbose_name='Apa sumber penerangan utama?')),
                ('r307b', models.CharField(blank=True, choices=[('1', '450 Watt'), ('2', '900 Watt'), ('3', '1.300 Watt'), ('4', '2.200 Watt'), ('5', '> 2.200 Watt')], max_length=1, null=True, verbose_name='Berapa daya yang terpasang di rumah ini?')),
                ('r308', models.CharField(choices=[('1', 'Listrik'), ('2', 'Gas Elpiji 5,5 Kg/Blue Gas'), ('3', 'Gas Elpiji 12 Kg'), ('4', 'Gas Elpiji 3 Kg'), ('5', 'Gas Kota'), ('6', 'Biogas'), ('7', 'Minyak Tanah'), ('8', 'Briket'), ('9', 'Arang'), ('10', 'Kayu Bakar'), ('11', 'Lainnya'), ('00', 'Tidak Memasak di Rumah')], max_length=2, verbose_name='Bahan bakar/energi utama untuk memasak?')),
                ('r309a', models.CharField(choices=[('1', 'Ada, digunakan hanya Anggota Keluarga sendiri'), ('2', 'Ada, digunakan bersama Anggota Keluarga dari keluarga tertentu'), ('3', 'Ada, di MCK komunal'), ('4', 'Ada, di MCK umum/siapapun menggunakan'), ('5', 'Ada, Anggota Keluarga tidak menggunakan'), ('6', 'Tidak ada fasilitas')], max_length=1, verbose_name='Kepemilikan dan penggunaan fasilitas tempat buang air besar?')),
                ('r309b', models.CharField(blank=True, choices=[('1', 'Leher Angsa'), ('2', 'Plengsengan dengan Tutup'), ('3', 'Plengsengan tanpa Tutup'), ('4', 'Cemplung/Cubluk')], max_length=1, null=True, verbose_name='Jenis kloset?')),
                ('r310', models.CharField(choices=[('1', 'Tangki Septik'), ('2', 'IPAL'), ('3', 'Kolam/Sawah/Sungai/Danau/Laut'), ('4', 'Lubang Tanah'), ('5', 'Pantai/Tanah Lapang/Kebun'), ('6', 'Lainnya')], max_length=1, verbose_name='Tempat pembuangan akhir tinja')),
                ('r501a', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Penerima Program Bantuan Sosial Sembako/ BPNT?')),
                ('r501b', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Penerima Program Keluarga Harapan (PKH)?')),
                ('r501c', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Penerima Program Bantuan Langsung Tunai (BLT) Desa?')),
                ('r501d', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Penerima Program Subsidi Listrik (Gratis/Pemotongan Biaya)?')),
                ('r501e', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Penerima Program Bantuan Pemerintah Daerah?')),
                ('r501f', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Penerima Program Bantuan Subsidi Pupuk?')),
                ('r501g', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Penerima Program Subsidi LPG?')),
                ('r501a_date', models.DateField(blank=True, null=True, verbose_name='Periode Terakhir Mendapatkan Program')),
                ('r501b_date', models.DateField(blank=True, null=True, verbose_name='Periode Terakhir Mendapatkan Program')),
                ('r501c_date', models.DateField(blank=True, null=True, verbose_name='Periode Terakhir Mendapatkan Program')),
                ('r501d_date', models.DateField(blank=True, null=True, verbose_name='Periode Terakhir Mendapatkan Program')),
                ('r501e_date', models.DateField(blank=True, null=True, verbose_name='Periode Terakhir Mendapatkan Program')),
                ('r501f_date', models.DateField(blank=True, null=True, verbose_name='Periode Terakhir Mendapatkan Program')),
                ('r501g_date', models.DateField(blank=True, null=True, verbose_name='Periode Terakhir Mendapatkan Program')),
                ('r502a', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Tabung gas 5,5 kg atau lebih?')),
                ('r502b', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Lemari Es/Kulkas?')),
                ('r502c', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Air Conditioner (AC)?')),
                ('r502d', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Pemanas Air (Water Heater)?')),
                ('r502e', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Telepon Rumah (PSTN)?')),
                ('r502f', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Televisi Layar Datar (Min. 30 Inci)?')),
                ('r502g', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Emas/Perhiasan (Min. 10 gram)?')),
                ('r502h', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Komputer/Laptop/Tablet?')),
                ('r502i', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Sepeda Motor?')),
                ('r502j', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Sepeda?')),
                ('r502k', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Mobil?')),
                ('r502l', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Perahu?')),
                ('r502m', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Kapal/Perahu Motor?')),
                ('r502n', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Smartphone?')),
                ('r503a', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Keluarga Memiliki Aset Lahan (selain yang ditempati)?')),
                ('r503b', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Keluarga Memiliki Aset Rumah/Bangunan di Tempat Lain?')),
                ('r504a', models.IntegerField(verbose_name='Jumlah ternak Sapi (ekor)?')),
                ('r504b', models.IntegerField(verbose_name='Jumlah ternak Kerbau (ekor)?')),
                ('r504c', models.IntegerField(verbose_name='Jumlah ternak Kuda (ekor)?')),
                ('r504d', models.IntegerField(verbose_name='Jumlah ternak Babi (ekor)?')),
                ('r504e', models.IntegerField(verbose_name='Jumlah ternak Kambing/Domba (ekor)?')),
                ('r505', models.IntegerField(choices=[('0', 'Tidak Menggunakan Internet'), ('1', 'Internet dan TV Digital Berlangganan'), ('2', 'WiFi'), ('3', 'Internet Handphone')], verbose_name='Jenis akses internet utama yang digunakan oleh keluarga?')),
                ('r506', models.IntegerField(choices=[('1', 'Ya, untuk Usaha'), ('2', 'Ya, untuk Pribadi'), ('3', 'Ya, untuk usaha dan pribadi'), ('4', 'Tidak')], verbose_name='Apakah keluarga ini memiliki rekening aktif atau dompet digital?')),
                ('updated_at', models.DateField(auto_now=True)),
                ('r104', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='families_location_by_region', to='app.regionadministrativemodels', verbose_name='Kode Desa/Kelurahan')),
                ('r105', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='families_location_by_sls', to='app.regionslsmodels', verbose_name='Kode SLS/Non SLS')),
            ],
            options={
                'verbose_name': 'Master Data Keluarga',
            },
        ),
    ]
