# Generated by Django 5.1 on 2024-09-05 04:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r106', models.TextField(max_length=256, verbose_name='Alamat Lengkap')),
                ('r107', models.CharField(max_length=128, verbose_name='Nama Kepala Keluarga')),
                ('r108', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Nomor Kartu Keluarga (KK)')),
                ('r109', models.IntegerField(verbose_name='Jumlah Anggota Keluarga')),
                ('r110', models.CharField(max_length=128, verbose_name='Nama Pemberi Informasi')),
                ('r201', models.CharField(max_length=128, verbose_name='Nama Pencacah')),
                ('r202', models.DateField(verbose_name='Tgl Kunjungan Pertama')),
                ('r203', models.DateField(verbose_name='Tgl Kunjungan Terakhir')),
                ('r204', models.CharField(max_length=128, verbose_name='Nama Pemeriksa')),
                ('r205', models.DateField(verbose_name='Tanggal Pemeriksaan')),
                ('r206', models.CharField(choices=[('1', 'Terisi Lengkap'), ('2', 'Tidak Terisi Lengkap')], max_length=1, verbose_name='Hasil Pencacahan')),
                ('r301', models.CharField(choices=[('1', 'Milik Sendiri'), ('2', 'Kontrak/Sewa'), ('3', 'Bebas Sewa'), ('4', 'Dipinjami'), ('5', 'Dinas'), ('6', 'Lainnya')], max_length=1, verbose_name='Status penguasan bangunan tempat tinggal yang ditempati')),
                ('r302', models.CharField(blank=True, choices=[('1', 'Milik Sendiri'), ('2', 'Milik Orang Lain'), ('3', 'Tanah Negara'), ('4', 'Lainnya')], max_length=1, null=True, verbose_name='Status lahan tempat tinggal yang ditempati')),
                ('r303', models.CharField(choices=[('1', 'Marmer/Granit'), ('2', 'Keramik'), ('3', 'Parket/Vini/Karpet'), ('4', 'Ubin/Tegel/Teraso'), ('5', 'Kayu/Papan'), ('6', 'Semen/Bata Merah'), ('7', 'Bambu'), ('8', 'Kayu/Papan Kualitas Rendah'), ('9', 'Tanah'), ('10', 'Lainnya')], max_length=2, verbose_name='Jenis lantai tempat tinggal terluas')),
                ('r304', models.CharField(choices=[('1', 'Tembok'), ('2', 'Plesteran Anyaman Bambu/Kawat'), ('3', 'Kayu/Papan/Gypsum/GRC/Calciboard'), ('4', 'Anyaman Bambu'), ('5', 'Batang Kayu'), ('6', 'Bambu'), ('7', 'Lainnya')], max_length=1, verbose_name='Jenis dinding terluas')),
                ('r305', models.CharField(choices=[('1', 'Ada, Berfungsi'), ('2', 'Ada, Tidak Berfungsi'), ('3', 'Tidak Ada')], max_length=1, verbose_name='Keberadaan jendela')),
                ('r306', models.CharField(choices=[('1', 'Beton/Genteng Beton'), ('2', 'Genteng Keramik'), ('3', 'Genteng Metal'), ('4', 'Genteng Tanah Liat'), ('5', 'Asbes'), ('6', 'Seng'), ('7', 'Sirap'), ('8', 'Bambu'), ('9', 'Jerami/Ijuk/Daun-daunan/Rumbia'), ('10', 'Lainnya')], max_length=2, verbose_name='Jenis atap terluas')),
                ('r307', models.CharField(choices=[('1', 'Listrik PLN dengan Meteran'), ('2', 'Listrik PLN tanpa Meteran'), ('3', 'Lampu Minyak/Lilin'), ('4', 'Sumber Penerangan Lainnya')], max_length=1, verbose_name='Sumber penerangan utama')),
                ('r308', models.CharField(choices=[('1', 'Tidak Ada'), ('2', 'Kebun/Sungai/Drainase'), ('3', 'Dibakar'), ('4', 'Tempat Sampah'), ('5', 'Tempat Sampah dan Diangkat Reguler')], max_length=1, verbose_name='Tempat pembuangan sampah')),
                ('r309', models.CharField(choices=[('1', 'Sendiri'), ('2', 'Bersama/Berkelompok'), ('3', 'MCK Umum'), ('4', 'Tidak Ada')], max_length=1, verbose_name='Fasilitas MCK')),
                ('r310', models.CharField(choices=[('1', 'Air Kemasan Bermerk'), ('2', 'Air Isi Ulang'), ('3', 'Leding Meteran'), ('4', 'Leding Eceran'), ('5', 'Sumur Terlindung'), ('6', 'Sumur Tak Terlindung'), ('7', 'Mata Air Terlindung'), ('8', 'Mata Air Tak Terlindung'), ('9', 'Air Hujan'), ('10', 'Lainnya')], max_length=2, verbose_name='Sumber air minum utama')),
                ('r401a', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Tanah/Lahan Pertanian')),
                ('r401b', models.IntegerField(verbose_name='Luas Lahan')),
                ('r402a', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Sapi')),
                ('r402b', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Kerbau')),
                ('r402c', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Kuda')),
                ('r402d', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Babi')),
                ('r402e', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Kambing/Domba')),
                ('r402f', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Domba')),
                ('r402g', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Ayam Buras')),
                ('r402h', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Ayam Ras Pedaging')),
                ('r402i', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Ayam Ras Petelur')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Data Keluarga',
                'verbose_name_plural': 'Master Data Keluarga',
            },
        ),
        migrations.CreateModel(
            name='RegionAdministrativeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_code', models.CharField(max_length=10, unique=True, verbose_name='Kode Wilayah')),
                ('reg_name', models.CharField(max_length=128, verbose_name='Nama Wilayah')),
            ],
            options={
                'verbose_name': 'Master Wilayah Administratif',
                'verbose_name_plural': 'Master Wilayah Administratif',
            },
        ),
        migrations.CreateModel(
            name='PopulationsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r501', models.IntegerField(verbose_name='Nomor Urut')),
                ('r502', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='NIK')),
                ('r503', models.CharField(max_length=128, verbose_name='Nama Lengkap')),
                ('r504', models.CharField(choices=[('1', 'Kepala keluarga'), ('2', 'Istri/suami'), ('3', 'Anak'), ('4', 'Menantu'), ('5', 'Cucu'), ('6', 'Orangtua/mertua'), ('7', 'Lainnya')], max_length=1, verbose_name='Hubungan dengan KK')),
                ('r505', models.CharField(choices=[('1', 'Tinggal Bersama Keluarga'), ('2', 'Meninggal'), ('3', 'Tidak Tinggal Bersama Keluarga/Pindah'), ('4', 'Anggota Keluarga Baru'), ('5', 'Tidak Ditemukan')], max_length=1, verbose_name='Keberadaan anggota keluarga')),
                ('r506', models.CharField(choices=[('1', 'Laki-laki'), ('2', 'Perempuan')], max_length=1, verbose_name='Jenis kelamin')),
                ('r507', models.CharField(max_length=128, verbose_name='Tempat lahir')),
                ('r508', models.DateField(verbose_name='Tanggal lahir')),
                ('r510', models.CharField(choices=[('1', 'Belum Kawin'), ('2', 'Kawin/Nikah'), ('3', 'Cerai Hidup'), ('4', 'Cerai Mati')], max_length=1, verbose_name='Status pernikahan')),
                ('r511', models.CharField(choices=[('1', 'Islam'), ('2', 'Kristen'), ('3', 'Katolik'), ('4', 'Hindu'), ('5', 'Budha'), ('6', 'Konghuchu')], max_length=1, verbose_name='Agama')),
                ('r512', models.CharField(choices=[('1', 'Muna'), ('2', 'Lainnya')], max_length=1, verbose_name='Suku')),
                ('r513', models.CharField(blank=True, choices=[('1', 'Bersekolah'), ('2', 'Mengurus Rumah Tangga'), ('3', 'Tidak Bekerja'), ('4', 'Sedang Mencari Pekerjaan'), ('5', 'Bekerja')], max_length=1, null=True, verbose_name='Kegiatan utama')),
                ('r514', models.CharField(blank=True, max_length=256, null=True, verbose_name='Pekerjaan utama')),
                ('r515', models.CharField(blank=True, choices=[('01', 'Pertanian tanaman padi & palawija'), ('02', 'Hortikultura'), ('03', 'Perkebunan'), ('04', 'Perikanan'), ('05', 'Peternakan'), ('06', 'Kehutanan & pertanian lainnya'), ('07', 'Pertambangan/penggalian'), ('08', 'Industri pengolahan'), ('09', 'Pengadaan listrik, gas, uap/air panas, dan udara dingin'), ('10', 'Pengelolaan air, pengelolaan air limbah, pengelolaan dan daur ulang sampah, dan aktivitas remediasi'), ('11', 'Konstruksi'), ('12', 'Perdagangan besar dan eceran, reparasi dan perawatan mobil dan sepeda motor'), ('13', 'Pengangkutan dan pergudangan'), ('14', 'Penyediaan akomodasi & makan minum'), ('15', 'Informasi & komunikasi'), ('16', 'Keuangan & asuransi'), ('17', 'Real estate'), ('18', 'Aktivitas profesional, ilmiah, dan teknis'), ('19', 'Aktivitas penyewaan dan sewa guna tanpa hak opsi, ketenagakerjaan, agen perjalanan, dan penunjang usaha lainnya'), ('20', 'Administrasi pemerintahan, pertahanan, dan jaminan sosial wajib'), ('21', 'Pendidikan'), ('22', 'Aktivitas kesehatan manusia dan aktivitas sosial'), ('23', 'Kesenian, hiburan, dan rekreasi'), ('24', 'Aktivitas jasa lainnya'), ('25', 'Aktivitas keluarga sebagai pemberi kerja'), ('26', 'Aktivitas badan internasional dan badan ekstra internasional lainnya')], max_length=2, null=True, verbose_name='Lapangan usaha')),
                ('r516', models.CharField(blank=True, max_length=256, null=True, verbose_name='Komoditas utama')),
                ('r517', models.CharField(blank=True, choices=[('1', 'Tidak/belum pernah sekolah'), ('2', 'Masih sekolah'), ('3', 'Tidak bersekolah lagi')], max_length=1, null=True, verbose_name='Partisipasi sekolah')),
                ('r518', models.CharField(blank=True, choices=[('1', 'Tidak/Belum Tamat SD'), ('2', 'SD/Sederajat'), ('3', 'SMP/Sederajat'), ('4', 'SMA/Sederajat'), ('5', 'D1/D2/D3'), ('6', 'S1/S2/S3')], max_length=1, null=True, verbose_name='Pendidikan tertinggi yang ditamatkan')),
                ('r519', models.CharField(blank=True, choices=[('0', 'Tidak memiliki'), ('1', 'BPJS PBI'), ('2', 'BPJS Non PBI'), ('3', 'Jamkes lainnya')], max_length=2, null=True, verbose_name='Jaminan kesehatan')),
                ('r520a', models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunanetra/buta')),
                ('r520b', models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunarungu/ tuli')),
                ('r520c', models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunawicara/ bisu')),
                ('r520d', models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunarungu–wicara tuli–bisu')),
                ('r520e', models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunadaksa/ cacat tubuh')),
                ('r520f', models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunagrahita')),
                ('r520g', models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunalaras')),
                ('r520h', models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Cacat Ganda')),
                ('r520i', models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Dipasung')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families_members', to='app.familiesmodels', verbose_name='ID Keluarga')),
            ],
            options={
                'verbose_name': 'Master Data Penduduk',
                'verbose_name_plural': 'Master Data Penduduk',
            },
        ),
        migrations.AddField(
            model_name='familiesmodels',
            name='r104',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='families_location_by_region', to='app.regionadministrativemodels', verbose_name='Kode Desa/Kelurahan'),
        ),
        migrations.CreateModel(
            name='RegionSLSModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_sls_code', models.CharField(max_length=6, unique=True, verbose_name='Kode SLS/Non SLS')),
                ('reg_sls_name', models.CharField(max_length=128, verbose_name='Nama SLS/Non SLS')),
                ('reg_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_administrative', to='app.regionadministrativemodels', verbose_name='Kode Desa/Kelurahan')),
            ],
            options={
                'verbose_name': 'Master SLS/Non SLS',
                'verbose_name_plural': 'Master SLS/Non SLS',
            },
        ),
        migrations.AddField(
            model_name='familiesmodels',
            name='r105',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='families_location_by_sls', to='app.regionslsmodels', verbose_name='Nama Dusun'),
        ),
    ]
