# Generated by Django 5.1 on 2024-09-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiesmodels',
            name='r302',
            field=models.CharField(choices=[('1', 'Milik Sendiri'), ('2', 'Milik Orang Lain'), ('3', 'Tanah Negara'), ('4', 'Lainnya')], default=1, max_length=1, verbose_name='Status lahan tempat tinggal yang ditempati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familiesmodels',
            name='r401a',
            field=models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Kepemilikan Tanah/Lahan Pertanian'),
        ),
        migrations.AlterField(
            model_name='familiesmodels',
            name='r401b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Luas Lahan'),
        ),
    ]
