# Generated by Django 5.1 on 2024-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familiesmodels',
            options={'verbose_name': 'Master Data Keluarga', 'verbose_name_plural': 'Master Data Keluarga'},
        ),
        migrations.AlterModelOptions(
            name='regionadministrativemodels',
            options={'verbose_name': 'Master Wilayah Administratif', 'verbose_name_plural': 'Master Wilayah Administratif'},
        ),
        migrations.AlterModelOptions(
            name='regionslsmodels',
            options={'verbose_name': 'Master SLS/Non SLS', 'verbose_name_plural': 'Master SLS/Non SLS'},
        ),
        migrations.AlterField(
            model_name='regionadministrativemodels',
            name='reg_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kode Wilayah'),
        ),
        migrations.AlterField(
            model_name='regionslsmodels',
            name='reg_sls_code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Kode SLS/Non SLS'),
        ),
    ]
