# Generated by Django 5.1 on 2024-09-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_familiesmodels_r302_alter_familiesmodels_r401a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populationsmodels',
            name='r520i',
        ),
    ]
