# Generated by Django 5.1 on 2024-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_familiesmodels_catatan_alter_familiesmodels_r301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiesmodels',
            name='r307',
            field=models.CharField(choices=[('1', 'listrik PLN'), ('2', 'Listrik Non PLN'), ('3', 'Lampu Minyak/Lilin'), ('4', 'Sumber Penerangan Lainnya')], max_length=1, verbose_name='Sumber penerangan utama'),
        ),
    ]
