# Generated by Django 5.1 on 2024-09-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_populationsmodels_r520i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiesmodels',
            name='r302',
            field=models.CharField(blank=True, choices=[('1', 'Milik Sendiri'), ('2', 'Milik Orang Lain'), ('3', 'Tanah Negara'), ('4', 'Lainnya')], max_length=1, null=True, verbose_name='Status lahan tempat tinggal yang ditempati'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520b',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunarungu/tuli'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520c',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunawicara/bisu'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520d',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunarungu–wicara/tuli–bisu'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520e',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, null=True, verbose_name='Tunadaksa/cacat tubuh'),
        ),
    ]
