# Generated by Django 5.1 on 2024-09-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_familiesmodels_r307'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiesmodels',
            name='r309b',
            field=models.CharField(choices=[('1', 'Leher Angsa'), ('2', 'Plengsengan'), ('3', 'Cemplung/Cubluk'), ('4', 'Tidak Ada')], default=4, max_length=1, verbose_name='Jenis kloset yang digunakan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiesmodels',
            name='r401c',
            field=models.CharField(blank=True, choices=[('1', 'Jagung'), ('2', 'Ubi'), ('3', 'Sayuran'), ('4', 'Jati'), ('5', 'Jambu Mete')], max_length=1, null=True, verbose_name='Jenis tanaman terluas'),
        ),
        migrations.AlterField(
            model_name='familiesmodels',
            name='r307',
            field=models.CharField(choices=[('1', 'Listrik PLN'), ('2', 'Listrik Non PLN'), ('3', 'Lampu Minyak/Lilin'), ('4', 'Sumber Penerangan Lainnya')], max_length=1, verbose_name='Sumber penerangan utama'),
        ),
    ]
