# Generated by Django 5.1 on 2024-09-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_familiesmodels_r302_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520a',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', max_length=1, null=True, verbose_name='Tunanetra/buta'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520b',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', max_length=1, null=True, verbose_name='Tunarungu/tuli'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520c',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', max_length=1, null=True, verbose_name='Tunawicara/bisu'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520d',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', max_length=1, null=True, verbose_name='Tunarungu–wicara/tuli–bisu'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520e',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', max_length=1, null=True, verbose_name='Tunadaksa/cacat tubuh'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520f',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', max_length=1, null=True, verbose_name='Tunagrahita'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520g',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', max_length=1, null=True, verbose_name='Tunalaras'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r520h',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', max_length=1, null=True, verbose_name='Cacat Ganda'),
        ),
    ]
