# Generated by Django 5.1 on 2024-08-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_populiationsmodels_alter_familiesmodels_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopuliationsModels',
            new_name='PopulationsModels',
        ),
    ]
