# Generated by Django 5.1 on 2024-09-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_familiesmodels_r309b_familiesmodels_r401c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiesmodels',
            name='r401c',
            field=models.CharField(blank=True, choices=[('1', 'Jagung'), ('2', 'Ubi'), ('3', 'Sayuran'), ('4', 'Jati'), ('5', 'Jambu Mete'), ('6', 'Lainnya')], max_length=1, null=True, verbose_name='Jenis tanaman terluas'),
        ),
    ]
