# Generated by Django 5.1 on 2024-08-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_populiationsmodels_populationsmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationsmodels',
            name='family_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='families_members', to='app.familiesmodels', verbose_name='ID Keluarga'),
            preserve_default=False,
        ),
    ]
