# Generated by Django 5.1 on 2024-09-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_familiesmodels_r401c'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiesmodels',
            name='cleaned_state',
            field=models.CharField(blank=True, choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', max_length=1, null=True, verbose_name='Status Dokumen'),
        ),
        migrations.AlterField(
            model_name='familiesmodels',
            name='r401c',
            field=models.CharField(blank=True, choices=[('1', 'Jagung'), ('2', 'Ubi'), ('3', 'Sayuran'), ('4', 'Jati'), ('5', 'Jambu Mete'), ('6', 'Lainnya'), ('7', 'Tidak Ditanami')], max_length=1, null=True, verbose_name='Jenis tanaman terluas'),
        ),
    ]
