# Generated by Django 5.1 on 2024-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_populationsmodels_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationsmodels',
            name='r427',
            field=models.CharField(blank=True, choices=[('1', 'Kurang Gizi (Wasting)'), ('2', 'Kerdil (Stunting)'), ('3', 'Tidak Ada Catatan'), ('4', 'Tidak Tahu')], max_length=1, null=True, verbose_name='Kondisi gizi anak dari pemeriksaan 3 bulan terakhir di posyandu/puskesmas/rumah sakit dengan mengacu pada buku kontrol (Umur 0-4)'),
        ),
    ]
