# Generated by Django 5.1 on 2024-09-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_familiesmodels_r108_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nama Petugas')),
                ('role', models.CharField(choices=[('1', 'Petugas Pendataan'), ('2', 'Petugas Lapangan')], max_length=1, verbose_name='Role Petugas')),
            ],
            options={
                'verbose_name': 'Daftar Petugas',
                'verbose_name_plural': 'Daftar Petugas',
            },
        ),
    ]
