# Generated by Django 5.1 on 2024-08-19 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_populationsmodels_r427'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationsmodels',
            name='r407',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Umur'),
        ),
    ]
