# Generated by Django 5.1 on 2024-08-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_populationsmodels_r407'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiesmodels',
            name='r115',
            field=models.CharField(default=9999999999999999, max_length=16, verbose_name='Nomor Kartu Keluarga (KK)'),
            preserve_default=False,
        ),
    ]
