# Generated by Django 5.1 on 2024-08-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_familiesmodels_r115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationsmodels',
            name='r430',
            field=models.CharField(blank=True, choices=[('01', 'Tidak Ada'), ('02', 'Hipertensi (darah tinggi)'), ('03', 'Rematik'), ('04', 'Asma'), ('05', 'Masalah jantung'), ('06', 'Diabetes (kencing manis)'), ('07', 'Tuberculosis (TBC)'), ('08', 'Stroke'), ('09', 'Kanker atau tumor ganas'), ('10', 'Gagal ginjal'), ('11', 'Haemophilia'), ('12', 'HIV/AIDS'), ('13', 'Kolesterol'), ('14', 'Sirosis Hati'), ('15', 'Thalasemia'), ('16', 'Leukimia'), ('17', 'Alzheimer'), ('18', 'Lainnya')], max_length=2, null=True, verbose_name='Memiliki keluhan kesehatan kronis/menahun?'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r431a',
            field=models.CharField(blank=True, choices=[('0', 'Tidak memiliki'), ('1', 'PBI JKN'), ('2', 'JKN Mandiri'), ('4', 'JKN Pemberi kerja'), ('8', 'Jamkes lainnya'), ('99', 'Tidak Tahu')], max_length=2, null=True, verbose_name='Dalam satu tahun terakhir, apakah memiliki jaminan kesehatan?'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r431f',
            field=models.CharField(blank=True, choices=[('0', 'Tidak memiliki'), ('1', 'BPJS Jaminan Kecelakaan Kerja'), ('2', 'BPJS Jaminan Kematian'), ('4', 'BPJS Jaminan Hari Tua'), ('8', 'BPJS Jaminan Pensiun'), ('16', 'Pensiun/Jaminan hari tua lainnya (Taspen/Program Pensiun Swasta)'), ('99', 'Tidak Tahu')], max_length=2, null=True, verbose_name='Dalam satu tahun terakhir, apakah (Nama) memiliki jaminan ketenagakerjaan?'),
        ),
    ]
