# Generated by Django 5.1 on 2024-08-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_familiesmodels_r504a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationsmodels',
            name='r403',
            field=models.CharField(max_length=16, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r406',
            field=models.DateField(verbose_name='Tanggal Lahir'),
        ),
    ]
