# Generated by Django 5.1 on 2024-08-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_populationsmodels_r403_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationsmodels',
            name='r403',
            field=models.CharField(max_length=16, unique=True, verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r406',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
    ]
