# Generated by Django 5.1 on 2024-08-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_populationsmodels_r403_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiesmodels',
            name='r115',
            field=models.CharField(max_length=16, unique=True, verbose_name='Nomor Kartu Keluarga (KK)'),
        ),
    ]
