# Generated by Django 5.1 on 2024-09-04 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_familiesmodels_r115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiesmodels',
            name='r115',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Nomor Kartu Keluarga (KK)'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r403',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Nomor Induk Kependudukan (NIK)'),
        ),
        migrations.AlterField(
            model_name='populationsmodels',
            name='r415',
            field=models.CharField(blank=True, choices=[('1', 'Paket A'), ('2', 'SDLB'), ('3', 'SD'), ('4', 'MI'), ('5', 'SPM/PDF Ula'), ('6', 'Paket B'), ('7', 'SMP LB'), ('8', 'SMP'), ('9', 'MTs'), ('10', 'SPM/PDF Wustha'), ('11', 'Paket C'), ('12', 'SMLB'), ('13', 'SMA'), ('14', 'MA'), ('15', 'SMK'), ('16', 'MAK'), ('17', 'SPM/PDF Ulya'), ('18', 'D1/D2/D3'), ('19', 'DIV/S1'), ('20', 'Profesi'), ('21', 'S2'), ('22', 'S3'), ('23', 'Tidak Punya Ijazah SD')], max_length=2, null=True, verbose_name='Ijazah/STTB tertinggi yang dimiliki'),
        ),
    ]
