# Generated by Django 5.1 on 2024-09-04 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_familiesmodels_r115_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiesmodels',
            name='r302',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Luas lantai bangunan tempat tinggal? ... m2'),
        ),
    ]
